### ISSUE TITLE
Development discussion

### ISSUE THREAD

**Issue by thegrumpylion** [dennwc/dom#18]
Hi @dennwc, many thanks for this awesome library. I have a lot of changes i want to push to this but before i start shipping tons of code, i want to ask if there's a way to contact you to discuss some general concepts i would like to see implemented and some changes i want to have in this.

I can also explain here in a ticket but since the ideas i have touch on some basic structures in the lib i would like some input first. I can always push to my fork of course and file a PR for you to see what i am talking about.

**Comment by dennwc** [comment]
Hi @thegrumpylion ! I'm happy to discuss any details, feel free to contact me on the Gophers Slack (#webassembly).
