### ISSUE TITLE
js\funcs.go:10:17: undefined: js.Callback

### ISSUE THREAD

**Issue by gshields** [dennwc/dom#19]
go version go1.12beta2 windows/amd64
Google Chrome Version 72.0.3626.81 (Official Build) (64-bit)

missing javascript

**Comment by dennwc** [comment]
Go 1.12 is not released yet. Use the [tip](https://github.com/dennwc/dom/tree/tip) branch instead.

**Comment by bfreis** [comment]
Any chance you could merge tip now, @dennwc ? :)
