### ISSUE TITLE
Replace syscall/js with gopherwasm

### ISSUE THREAD

**Issue by noartem** [dennwc/dom#23]
Replace `syscall/js` with [`gopherwasm/js`](https://github.com/gopherjs/gopherwasm/).

> GopherWasm is a wrapper for GopherJS (gopherjs/js) and Wasm (syscall/js). With this, you can make your application work with both GopherJS and Wasm.
>  GopherWasm's API emulates syscall/js, so please refer syscall/js API document to know how to use API of GopherWasm.

This will allow to compile the programs for wasm and gopherjs without any changes.

**Comment by dennwc** [comment]
I don't think adding yet another wrapper library to this one is a good idea. Maybe it will be better to inline that code for GopherJS into this library?

Unfortunately, I don't have time to work on it right now. So feel free to open a PR if you are interested in contributing it.
