### ISSUE TITLE
go 1.12 breaking changes

### ISSUE THREAD

**Issue by ladydascalie** [dennwc/dom#32]
As detailed here: https://golang.org/doc/go1.12#syscall/js

The changes made to `syscall/js` have now broken certain parts of the library.

I'd like to know wether or not this is something you are working on.
If not, I'm happy to start looking into it and helping out where able.

**Comment by dennwc** [comment]
Sorry for the late reply. The library was updated to support Go 1.12 recently, and CI seems to [pass](https://travis-ci.com/dennwc/dom/jobs/184720533) as well. Can you please attach a specific error you see?

**Comment by ladydascalie** [comment]
Hi @dennwc 

your recent update has fixed the issues I was having, so issue closed from my point of view!
Thanks for your great work.
