### ISSUE TITLE
Build strings breaks godoc

### ISSUE THREAD

**Issue by miketonks** [dennwc/dom#33]
It is useful to be able to read the documentation on godoc.

https://godoc.org/github.com/dennwc/dom

Unfortunately the build strings in this project hide the code from the godoc system, which presumably wants to build for linux.

```
//+build wasm,js
```

This doesn't seem to be an issue for other projects.  Do we really need the build strings?

https://godoc.org/honnef.co/go/js/dom

**Comment by dennwc** [comment]
Agree, will see what I can do to make it go-get-able and show the doc at the same time.

**Comment by dennwc** [comment]
[Fixed](https://github.com/dennwc/dom/pull/34) in master.

**Comment by miketonks** [comment]
Awesome - thanks!
