### ISSUE TITLE
Getting an element value ? 

### ISSUE THREAD

**Issue by HarishHary** [dennwc/dom#38]
Trying to do the same thing as this issue => #6 but I think I still miss something ?
In my situation, I have input fields inside a form, can you provide a way to manipulate forms ?
I noticed that looping over the nodeList we got more elements than the actual form ? Any insight on that ?

```
form := dom.Doc.GetElementById("custom_form")
btn := dom.Doc.GetElementById("btn")
t := document.Call("getElementById", "target")
logger := log.New((*writer)(&t), "", log.LstdFlags)

btn.AddEventListener("click", func(_ dom.Event) {
	nodes := form.ChildNodes()
	for _, element := range nodes {
		logger.Print("ID: " + string(element.Id()) + " Value: " + string(element.JSValue().Get("value").String()))
	}
})
```

**Comment by smoyer64** [comment]
Child nodes include both text elements nodes - you're only interested in the element nodes.  This behavior is correct according to the most recent specification (which deprecates attributes as child nodes) but might seem inconvenient.  One way to achieve what you want is to change your for loop as follows:

```go
	for _, element := range nodes {
		if element.TagName() != "" {
			logger.Print("ID: " + string(element.Id()) + " Value: " + string(element.JSValue().Get("value").String()))
		}
	}
```

**Comment by smoyer64** [comment]
After commit 61179be71e44b3446843f3b1af9535a22023758a, the test in my previous comment can be written as ``e.NodeType() == ElementNode``.

**Comment by HarishHary** [comment]
Thanks !
