### ISSUE TITLE
Cannot make it to work with go modules

### ISSUE THREAD

**Issue by Kerrex** [dennwc/dom#42]
Hello,
quick note: I'm go newbie and I've never encountered similar error with other go packages.
I'm trying to use this package using go modules (`go.mod`). Unfortunately, it seems like only `color.go` file is visible. Here are my project files:

go.mod:
    
    module goasmf

    go 1.12

    require github.com/dennwc/dom v0.3.0

main.go:
    
    package goasmf

    import (
 	    "fmt"
 	    "github.com/dennwc/dom"
    )

    func main() {
	    println("Testing WebAsm!")
	    var color dom.Color = "red"
	    dom.GetWindow()
    }

`go build` output:

    tomek$ go build
    # goasmf
    ./main.go:13:2: undefined: dom.GetWindow

Working without modules and downloading dependency using `go get -t github.com/dennwc/dom` works fine, though

**Comment by dennwc** [comment]
Hi @Kerrex!

The problem is not with Go modules, but rather with `go build`. This package expects to be built for WebAssembly and won't work for other architectures (except special packages like `./net/ws`). Use `GOOS` and `GOARCH` flags for the build command to set the correct architecture:
```bash
GOOS=js GOARCH=wasm go build
```

**Comment by Kerrex** [comment]
Thanks @dennwc! 
Now it makes sense why linting and autosuggesting in VSCode didn't work :) After adding flags to `settings.json` everything seems to work fine.
