### ISSUE TITLE
Possibly add instructions for getting autocomplete working in vscode?

### ISSUE THREAD

**Issue by DonMcNamara** [dennwc/dom#8]
After a little struggle I was able to get autocomplete working in VS code by setting some workspace level environment variables. I'm not sure how well known that is. Do you think it is worth adding to the README in this project?

I will gladly open a PR, but if you don't think this is the right place that is understandable.

**Comment by DonMcNamara** [comment]
(It is more applicable to working with web assembly in general than this project in particular.)

**Comment by dennwc** [comment]
It might be worth mentioning, for example linking to https://github.com/golang/go/wiki/WebAssembly. PRs are welcome :)
